# Generated by Django 6.0.5 on 2026-05-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("litreview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tickets_images/"),
        ),
    ]
