"""
Django settings for configuration project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

from pathlib import Path

# ======================================================================
# Chemins du projet
# ======================================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ======================================================================
# Sécurité et mode développement
# ======================================================================


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--cw=i#c%@@w%zm&6cs8v9z3u!p7^x3ts(a)*1b5v%(##dx7d50"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ======================================================================
# Applications installées
# ======================================================================

INSTALLED_APPS = [
    # Applications Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Applications externes
    "crispy_forms",
    "crispy_bootstrap5",
    # Applications projet
    "litreview",
]


# ======================================================================
# Utilisateur personnalisé
# ======================================================================

AUTH_USER_MODEL = "litreview.User"


# ======================================================================
# Middlewares
# ======================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ======================================================================
# URLs et WSGI
# ======================================================================

ROOT_URLCONF = "configuration.urls"

WSGI_APPLICATION = "configuration.wsgi.application"


# ======================================================================
# Templates
# ======================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ======================================================================
# Base de données
# ======================================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ======================================================================
# Validation des mots de passe
# ======================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ======================================================================
# Internationalisation
# ======================================================================

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True


# ======================================================================
# Fichiers statiques et médias
# ======================================================================

STATIC_URL = "static/"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# ======================================================================
# Authentification
# ======================================================================

LOGIN_URL = "connexion"
LOGIN_REDIRECT_URL = "accueil"
LOGOUT_REDIRECT_URL = "connexion"


# ======================================================================
# Crispy Forms / Bootstrap 5
# ======================================================================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
